#!/usr/bin/env bash
# Generates Pydantic models from the trace schema (shared/schemas/trace.schema.json).
# Run from anywhere; the output is checked in and CI fails if it is out of date.
#   backend/scripts/gen_types.sh
set -euo pipefail

backend="$(cd "$(dirname "$0")/.." && pwd)"
cd "$backend"

uv run --no-sync datamodel-codegen \
    --input ../shared/schemas/trace.schema.json \
    --input-file-type jsonschema \
    --output src/flow_tracer_api/generated/trace_schema.py \
    --output-model-type pydantic_v2.BaseModel \
    --target-python-version 3.12 \
    --use-annotated \
    --use-standard-collections \
    --use-union-operator \
    --field-constraints \
    --use-double-quotes \
    --use-schema-description \
    --use-field-description \
    --enum-field-as-literal all \
    --extra-fields forbid \
    --collapse-root-models \
    --disable-timestamp \
    --custom-file-header "# Generated by backend/scripts/gen_types.sh from shared/schemas/trace.schema.json. Do not edit." \
    --formatters ruff-format ruff-check
