// Generates the TypeScript types in src/generated/ (checked in; CI fails on a diff):
//   trace.ts     from ../shared/schemas/trace.schema.json   (json-schema-to-typescript)
//   openapi.json the backend's OpenAPI document             (FastAPI app via uv, see ADR 0003)
//   api.ts       from openapi.json                          (openapi-typescript)
// Usage: pnpm gen:types   (needs uv and the backend's dependencies: uv sync in ../backend)
import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { compileFromFile } from "json-schema-to-typescript";
import openapiTS, { astToString } from "openapi-typescript";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const out = path.join(root, "src/generated");
const schemaFile = path.join(root, "../shared/schemas/trace.schema.json");
const backend = path.join(root, "../backend");

const banner = (source) =>
  `/* Generated by scripts/gen-types.mjs from ${source}. Do not edit; run pnpm gen:types. */\n`;

await mkdir(out, { recursive: true });

// 1. Trace payload
const trace = await compileFromFile(schemaFile, {
  bannerComment: banner("shared/schemas/trace.schema.json").trim(),
  additionalProperties: false,
  strictIndexSignatures: true,
  style: { printWidth: 100 },
});
await writeFile(path.join(out, "trace.ts"), trace);

// 2. OpenAPI document of the backend
const openapi = execFileSync(
  "uv",
  ["run", "--quiet", "--project", backend, "python", path.join(root, "scripts/dump_openapi.py")],
  { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] },
);
await writeFile(path.join(out, "openapi.json"), openapi);

// 3. API types
const ast = await openapiTS(JSON.parse(await readFile(path.join(out, "openapi.json"), "utf8")));
await writeFile(
  path.join(out, "api.ts"),
  banner("the backend's OpenAPI document") + astToString(ast),
);

console.log("generated src/generated/{trace.ts,openapi.json,api.ts}");
